/** Public surface of the visual layer. Notes and widgets import from '@/components/viz' only. */
export { EChart } from './EChart'
export { XYChart, type XYSeries, type Segment } from './XYChart'
export { Heatmap, type HeatmapOverlay } from './Heatmap'
export { Interactive, Readout } from './Interactive'
export { ParamSlider, ParamChoice, ParamSwitch, ParamButton } from './controls'
export { StepControls } from './StepControls'
export { useParam, type Param, type ParamSpec } from './param'
export type { Handle, Vec2 } from './handles'
export { seriesColor, sequential, diverging } from './palette'
export { formatNumber } from './theme'
