/**
 * `aifn/metrics`: one implementation of every metric the site has a note on, each a function carrying its metadata
 * (`info`: key, display name, input kind, direction, range, the note that defines it and the model capability it
 * needs), so the lab and `estimators.evaluate` can use metrics generically through `metricRegistry`.
 *
 * - Foundations: confusion matrices and their margins (`confusionMargins`: totals, recall and precision per class),
 *   one-against-rest counts, `binaryRates`, averaging (`binary`, `micro`, `macro`, `weighted`, `samples`), Wilson and
 *   Wald intervals, the case and cluster bootstrap of any metric (from a stream), paired bootstraps, DeLong's AUROC
 *   variance and test.
 * - Classification: accuracy, balanced accuracy, precision, recall, F-β, specificity, NPV, FPR, FNR, informedness,
 *   markedness, Jaccard, MCC, Cohen's κ (weighted), Hamming loss, exact match, likelihood ratios, ordinal metrics.
 * - Curves (typed objects with `kind`): ROC, precision–recall, precision–recall–gain, DET, cost, gain and lift, the ROC
 *   convex hull; AUROC (ties as ½, multiclass OvR and Hand–Till), partial AUROC, average precision, EER, Youden, rates
 *   at a constraint; the binormal model's closed forms.
 * - Probabilistic: log loss, Brier (with Murphy's decomposition), spherical, reliability diagrams, ECE, MCE, RMS and
 *   debiased calibration errors, confidence and classwise ECE, ECE sweep, consistency bars, CRPS, log score, interval
 *   score, coverage, PIT, perplexity.
 * - Regression and forecasting; ranking and beyond-accuracy; clustering (external and internal); correlation and
 *   agreement; distances, Procrustes and Hausdorff; detection and segmentation; text; image and audio; generative
 *   models; fairness.
 *
 * Conventions: the target (truth, reference) comes first and the prediction second. Undefined ratios are NaN unless an
 * option says otherwise; nothing is clipped silently. Curves predict positive at score ≥ threshold. nDCG's gain is
 * explicit and defaults to 2^rel − 1. Arrays of numbers are returned as tensors.
 */

export {
  defineMetric,
  isMetric,
  type Capability,
  type Data,
  type InputKind,
  type Label,
  type Labels,
  type Metric,
  type MetricFunction,
  type MetricInfo,
  type Rows,
} from './core'
export {
  averaged,
  binaryCounts,
  binaryRates,
  confusionMargins,
  confusionMatrix,
  countsAtThreshold,
  oneVsRest,
  perClass,
  tallies,
  type Average,
  type AverageOptions,
  type BinaryCounts,
  type BinaryRates,
  type ConfusionMargins,
  type ConfusionMatrix,
  type ConfusionOptions,
  type CountStatistic,
  type OneVsRestCounts,
  type Tallies,
} from './confusion'
export {
  accuracy,
  balancedAccuracy,
  cohensKappa,
  diagnosticOddsRatio,
  errorRate,
  exactMatch,
  f1,
  fBeta,
  falseNegativeRate,
  falsePositiveRate,
  hammingLoss,
  informedness,
  jaccardScore,
  kappaFromTable,
  macroMeanAbsoluteError,
  markedness,
  matthewsCorrelation,
  negativeLikelihoodRatio,
  negativePredictiveValue,
  ordinalMeanAbsoluteError,
  positiveLikelihoodRatio,
  precision,
  precisionRecallFscoreSupport,
  quadraticWeightedKappa,
  recall,
  specificity,
  withinToleranceAccuracy,
  type ClassificationInput,
  type KappaWeights,
} from './classification'
export {
  auroc,
  averagePrecision,
  binormalAuroc,
  binormalAveragePrecision,
  binormalCurves,
  binormalEqualErrorRate,
  binormalRates,
  costCurve,
  detCurve,
  eer,
  equalErrorRate,
  gainCurve,
  normalisedExpectedCost,
  operatingPoint,
  partialAuroc,
  precisionRecallCurve,
  precisionRecallGainCurve,
  precisionRecallTrapezoid,
  recallAtPrecision,
  rocConvexHull,
  rocCurve,
  specificityAtSensitivity,
  tprAtFpr,
  trapezoidArea,
  youdenPoint,
  type AurocOptions,
  type OperatingPoint,
  type PrecisionRecallCurve,
  type RocCurve,
} from './curves'
export {
  brierDecomposition,
  brierScore,
  classwiseCalibrationError,
  confidenceCalibrationError,
  consistencyBars,
  coverage,
  crpsEnsemble,
  crpsGaussian,
  debiasedSquaredCalibrationError,
  expectedCalibrationError,
  gaussianLogScore,
  intervalScore,
  logLoss,
  maximumCalibrationError,
  perplexity,
  pitValues,
  reliabilityDiagram,
  rmsCalibrationError,
  sphericalScore,
  sweepCalibrationError,
  type BinStrategy,
  type BrierDecomposition,
  type Interval,
  type PerCase,
  type Probabilities,
  type ReliabilityDiagram,
} from './probabilistic'
export {
  adjustedR2Score,
  explainedVariance,
  gammaDeviance,
  huberLoss,
  logCoshError,
  maxError,
  meanAbsoluteError,
  meanAbsolutePercentageError,
  meanAbsoluteScaledError,
  meanSquaredError,
  meanSquaredLogError,
  medianAbsoluteError,
  normalisedRootMeanSquaredError,
  pinballLoss,
  poissonDeviance,
  r2Score,
  rootMeanSquaredError,
  rootMeanSquaredScaledError,
  symmetricMeanAbsolutePercentageError,
  tweedieDeviance,
  tweedieUnitDeviance,
  weightedMeanAbsolutePercentageError,
  type RegressionOptions,
  type ScaledErrorOptions,
} from './regression'
export {
  catalogueCoverage,
  dcg,
  expectedReciprocalRank,
  giniCoefficient,
  herfindahlIndex,
  hitRate,
  intraListDiversity,
  meanAveragePrecision,
  meanReciprocalRank,
  ndcg,
  novelty,
  precisionAtK,
  rPrecision,
  recallAtK,
  type AtKOptions,
  type DcgOptions,
  type Gain,
  type RankingInput,
  type RecallOptions,
} from './ranking'
export {
  adjustedMutualInformation,
  adjustedRandIndex,
  calinskiHarabasz,
  completeness,
  contingencyTable,
  daviesBouldin,
  dunnIndex,
  fowlkesMallows,
  homogeneity,
  homogeneityCompletenessV,
  mutualInformation,
  normalisedMutualInformation,
  pairConfusion,
  randIndex,
  silhouetteSamples,
  silhouetteScore,
  vMeasure,
  variationOfInformation,
  type Contingency,
  type EntropyMean,
} from './clustering'
export {
  chiSquareStatistic,
  concordanceCorrelation,
  contingencyCoefficient,
  cramersV,
  fleissKappa,
  intraclassCorrelation,
  kendallCorrelation,
  krippendorffAlpha,
  pearsonCorrelation,
  spearmanCorrelation,
  theilsU,
  tschuprowT,
  type IccForm,
  type MeasurementLevel,
} from './agreement'
export {
  angularDistance,
  chebyshevDistance,
  cosineDistance,
  cosineSimilarity,
  euclideanDistance,
  hausdorffDistance,
  hausdorffDistances,
  mahalanobisDistance,
  manhattanDistance,
  minkowskiDistance,
  orthogonalProcrustes,
  pairwiseDistances,
  procrustesDisparity,
  type HausdorffDistances,
  type PairwiseMetric,
  type Procrustes,
} from './distances'
export {
  averagePrecisionFromMatches,
  boundaryF1,
  boxIou,
  boxIouMatrix,
  boxOverlap,
  cocoIouThresholds,
  detectionAveragePrecision,
  detectionMeanAveragePrecision,
  dice,
  generalisedDice,
  iouPerClass,
  maskBoundary,
  maskIou,
  matchDetections,
  meanIou,
  panopticFromMatches,
  panopticQuality,
  type ApInterpolation,
  type Box,
  type BoxOverlap,
  type Detection,
  type GroundTruthObject,
  type Match,
} from './detection'
export {
  backretrieval,
  bertScore,
  bleu,
  bleuScore,
  characterErrorRate,
  chrF,
  chrFScore,
  editAlignment,
  longestCommonSubsequence,
  matchErrorRate,
  ngrams,
  normaliseAnswer,
  rougeL,
  rougeLScores,
  rougeN,
  rougeNScores,
  squadExactMatch,
  squadF1,
  translationEditRate,
  translationEdits,
  whitespaceTokens,
  wordErrorRate,
  wordInformationLost,
  words,
  type Alignment,
  type BleuOptions,
  type BleuResult,
  type BleuSmoothing,
  type EditOperation,
  type Prf,
  type References,
  type Text,
  type Tokeniser,
} from './text'
export {
  ergas,
  permutationInvariantScore,
  psnr,
  rase,
  siSdr,
  snr,
  spectralAngle,
  ssim,
  ssimMap,
  type Image,
  type SsimOptions,
} from './signal'
export {
  clipScore,
  densityCoverage,
  fid,
  frechetDistance,
  generativePrecisionRecall,
  inceptionScore,
  inceptionScoreSplits,
  kid,
  kidSubsets,
  type FrechetDistance,
  type PolynomialKernel,
} from './generative'
export {
  demographicParityDifference,
  demographicParityRatio,
  equalOpportunityDifference,
  equalisedOddsDifference,
  groupRates,
  predictiveParityDifference,
  type FairnessOptions,
  type GroupRates,
} from './fairness'
export {
  aurocDeLong,
  bootstrapMetric,
  delongTest,
  pairedBootstrap,
  waldInterval,
  wilsonInterval,
  type BootstrapOptions,
  type Cases,
  type MetricBootstrap,
} from './uncertainty'
export { getMetric, isBetter, listMetrics, metricRegistry } from './registry'
