import { createElement } from 'react'
import {
  Activity,
  ArrowRightLeft,
  AudioWaveform,
  Blend,
  BookOpen,
  Brain,
  ChartArea,
  ChartSpline,
  Cpu,
  Dices,
  Eye,
  FlaskConical,
  Folder,
  Gamepad2,
  GitFork,
  GraduationCap,
  Languages,
  LibraryBig,
  Gauge,
  Microscope,
  Network,
  Radar,
  Repeat,
  Ruler,
  Shapes,
  ShieldCheck,
  SlidersHorizontal,
  Sigma,
  Tags,
  Target,
  TrendingDown,
  Workflow,
  Grid3x3,
  Layers,
  MessageSquareText,
  Sparkles,
  Waves,
  Share2,
  Fingerprint,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react'
import type { CategoryIcon } from '@/lib/content-schema'

const icons: Record<CategoryIcon, LucideIcon> = {
  sigma: Sigma,
  target: Target,
  shapes: Shapes,
  'chart-spline': ChartSpline,
  bell: ChartArea,
  network: Network,
  cpu: Cpu,
  'book-open': BookOpen,
  brain: Brain,
  gauge: Gauge,
  dices: Dices,
  workflow: Workflow,
  microscope: Microscope,
  'git-fork': GitFork,
  'graduation-cap': GraduationCap,
  'trending-down': TrendingDown,
  ruler: Ruler,
  radar: Radar,
  activity: Activity,
  'audio-waveform': AudioWaveform,
  grid: Grid3x3,
  layers: Layers,
  'message-square': MessageSquareText,
  sparkles: Sparkles,
  waves: Waves,
  share: Share2,
  fingerprint: Fingerprint,
  gamepad: Gamepad2,
  languages: Languages,
  eye: Eye,
  sliders: SlidersHorizontal,
  library: LibraryBig,
  flask: FlaskConical,
  shield: ShieldCheck,
  blend: Blend,
  tags: Tags,
  repeat: Repeat,
  'arrow-right-left': ArrowRightLeft,
}

/** A top-level topic's icon from taxonomy.yaml, or a folder when it has none. */
export function TopicIcon({ icon, ...props }: { icon: CategoryIcon | undefined } & LucideProps) {
  return createElement(icon ? icons[icon] : Folder, props)
}
