import {
  Activity,
  AudioWaveform,
  BookOpen,
  Brain,
  ChartArea,
  ChartSpline,
  Cpu,
  Dices,
  Eye,
  Folder,
  Gamepad2,
  GitFork,
  GraduationCap,
  Languages,
  LibraryBig,
  Gauge,
  Microscope,
  Network,
  Radar,
  Ruler,
  Shapes,
  SlidersHorizontal,
  Sigma,
  Target,
  TrendingDown,
  Workflow,
  type LucideIcon,
} from 'lucide-react'
import type { CategoryIcon } from '@/lib/content-schema'

const icons: Record<CategoryIcon, LucideIcon> = {
  sigma: Sigma,
  target: Target,
  shapes: Shapes,
  'chart-spline': ChartSpline,
  bell: ChartArea,
  network: Network,
  cpu: Cpu,
  'book-open': BookOpen,
  brain: Brain,
  gauge: Gauge,
  dices: Dices,
  workflow: Workflow,
  microscope: Microscope,
  'git-fork': GitFork,
  'graduation-cap': GraduationCap,
  'trending-down': TrendingDown,
  ruler: Ruler,
  radar: Radar,
  activity: Activity,
  'audio-waveform': AudioWaveform,
  gamepad: Gamepad2,
  languages: Languages,
  eye: Eye,
  sliders: SlidersHorizontal,
  library: LibraryBig,
}

export function categoryIcon(icon: CategoryIcon | undefined): LucideIcon {
  return icon ? icons[icon] : Folder
}
