/** The lab's layout: the figure frame, the app shell and small typographic pieces. Import from '@lab/layout'. */
export { Figure, type FigureProps } from './Figure'
export { Columns } from './Columns'
export { ControlRow, Controls } from './Controls'
export { PanelSlot } from './slots'
export { FrameSlotsContext, type SlotName } from './slots-context'
export { Dashboard, DashboardCell, DashboardRow } from './Dashboard'
export { FigureScope, FIGURE_SIZES, type FigureSize } from './figure-size'
export { Shell, type LabPage } from './Shell'
export { Providers } from './Providers'
export { ThemeToggle } from './ThemeToggle'
export { Tex } from './Tex'
export { FigurePage } from './FigurePage'
export { slugify, specimenPath } from './paths'
export { Equation, EquationSteps, type EquationStep } from './Equation'
export { live, tex, toTex, type EquationTemplate, type LiveValue } from './equation-tex'
