import { useMemo, useState } from 'react'
import {
  ControlRow,
  Curve,
  Figure,
  Player,
  Plot,
  Plots,
  Points,
  Raster,
  Readout,
  Select,
  formatNumber,
  useAxis,
} from 'aifn-render'
import { normals, stream } from 'aifn/foundation/random'
import { moons, pinwheel } from 'aifn-methods/data/synthetic'
import { jemRun, type JemCheckpoint, type JemRun, type JemTrack } from 'aifn-methods/generative/energy'

const DATASETS = [
  { value: 'moons', label: 'Two moons (non-linear separation)' },
  { value: 'pinwheel', label: 'Pinwheel (multi-modal petals)' },
]

const MODELS = [
  { value: 'jem', label: 'JEM (Cross-Entropy + Contrastive Divergence)' },
  { value: 'ce', label: 'Standard Cross-Entropy Classifier' },
]

const VIEWS = [
  { value: 'energy', label: 'Energy surface E(x) = -logsumexp f(x)' },
  { value: 'prob', label: 'Predictive confidence P(y = 1 | x)' },
]

export function JemExplorer() {
  const [dataChoice, setDataChoice] = useState<'moons' | 'pinwheel'>('moons')
  const [modelType, setModelType] = useState<'jem' | 'ce'>('jem')
  const [viewType, setViewType] = useState<'energy' | 'prob'>('energy')
  const [checkpointIndex, setCheckpointIndex] = useState(0)

  const steps = 150

  // Run the JEM simulation
  const runResult = useMemo(() => {
    const s = stream(`jem-${dataChoice}`)
    const sTest = stream(`jem-${dataChoice}-test`)
    const sOod = stream(`jem-${dataChoice}-ood`)

    let rawData
    let testData
    if (dataChoice === 'moons') {
      rawData = moons(s, { n: 300, noise: 0.1 })
      testData = moons(sTest, { n: 100, noise: 0.1 })
    } else {
      rawData = pinwheel(s, { n: 300, arms: 2, noise: 0.05 })
      testData = pinwheel(sTest, { n: 100, arms: 2, noise: 0.05 })
    }
    const ood = { x: normals(sOod, [100, 2]) }

    const gen = jemRun(rawData, testData, ood, {
      steps,
      hidden: [32, 32],
      grid: 36,
      checkpoints: 10,
      seed: 42,
    })

    let last: JemRun | null = null
    for (const snap of gen) {
      last = snap
    }
    return last
  }, [dataChoice, steps])

  const run = runResult
  const track: JemTrack | null = useMemo(() => {
    if (!run) return null
    return (modelType === 'jem' ? (run as any).jem : (run as any).ce) ?? null
  }, [run, modelType])

  const checkpoints = track?.checkpoints ?? []
  const numCheckpoints = checkpoints.length
  const currentIdx = Math.min(checkpointIndex, Math.max(0, numCheckpoints - 1))
  const currentCheckpoint: JemCheckpoint | null = checkpoints[currentIdx] ?? null

  const box = run?.box ?? 3.5
  const gridAxis = useMemo(() => (run ? Array.from(run.gridX) : []), [run])

  // Training data points
  const trainPoints = useMemo(() => {
    if (!run) return { c0: { x: [], y: [] }, c1: { x: [], y: [] } }
    const flat = (run as any).data ?? new Float64Array()
    const labels = (run as any).labels ?? new Int32Array()
    const n = Math.min(200, flat.length / 2)
    const c0X: number[] = []
    const c0Y: number[] = []
    const c1X: number[] = []
    const c1Y: number[] = []

    for (let i = 0; i < n; i++) {
      const x = flat[2 * i]
      const y = flat[2 * i + 1]
      const l = labels[i]
      if (l === 0) {
        c0X.push(x)
        c0Y.push(y)
      } else {
        c1X.push(x)
        c1Y.push(y)
      }
    }
    return { c0: { x: c0X, y: c0Y }, c1: { x: c1X, y: c1Y } }
  }, [run])

  // Negative samples generated by Langevin dynamics (SGLD)
  const negativeSamples = useMemo(() => {
    if (!currentCheckpoint || !currentCheckpoint.samples || modelType === 'ce') {
      return { x: [], y: [] }
    }
    const flat = currentCheckpoint.samples
    const n = flat.length / 2
    const xs: number[] = []
    const ys: number[] = []
    for (let i = 0; i < n; i++) {
      xs.push(flat[2 * i])
      ys.push(flat[2 * i + 1])
    }
    return { x: xs, y: ys }
  }, [currentCheckpoint, modelType])

  // Raster surface (Energy E(x) or probability p(y=1 | x))
  const surfaceMatrix = useMemo(() => {
    if (!currentCheckpoint || !run) return []
    const g = run.gridX.length
    const logits = currentCheckpoint.logits
    const K = run.classes ?? 2
    const m: number[][] = []

    for (let i = 0; i < g; i++) {
      const row: number[] = []
      for (let j = 0; j < g; j++) {
        const offset = (i * g + j) * K
        const f0 = logits[offset] ?? 0
        const f1 = logits[offset + 1] ?? 0

        if (viewType === 'energy') {
          // E(x) = -log(e^f0 + e^f1) = -max(f0, f1) - log(1 + exp(-|f0 - f1|))
          const maxF = Math.max(f0, f1)
          const energy = -(maxF + Math.log(1 + Math.exp(-Math.abs(f0 - f1))))
          row.push(energy)
        } else {
          // p(y=1 | x) = sigmoid(f1 - f0)
          const diff = f1 - f0
          const prob = 1 / (1 + Math.exp(-diff))
          row.push(prob)
        }
      }
      m.push(row)
    }
    return m
  }, [currentCheckpoint, run, viewType])

  const planeAxisX = useAxis({ label: 'x₁', range: [-box, box] })
  const planeAxisY = useAxis({ label: 'x₂', range: [-box, box] })

  const lossSteps = useMemo(() => {
    const len = track?.crossEntropy.length ?? 0
    return Array.from({ length: len }, (_, i) => i + 1)
  }, [track])

  const ceLoss = useMemo(() => {
    if (!track) return []
    return Array.from(track.crossEntropy)
  }, [track])

  const lossX = useAxis({ label: 'Update step', range: [0, Math.max(1, lossSteps.length)] })
  const lossY = useAxis({ label: 'Cross-entropy loss', range: [0, 2] })

  const meanDataEnergy = track && track.dataEnergy ? track.dataEnergy[track.dataEnergy.length - 1] : NaN

  return (
    <Figure
      title="Joint Energy-Based Models (JEM) & SGLD Sampling"
      purpose="Compare JEM and Softmax Cross-Entropy on energy landscape calibration, OOD detection, and SGLD Langevin sampling."
      caption={
        'Joint Energy-based Model vs standard Cross-Entropy Classifier (Grathwohl et al., 2020). JEM trains the classifier logits f(x)[y] as an unnormalised energy model E(x) = -logsumexp f(x) alongside the classification cross-entropy. A standard classifier assigns confident probabilities far away from data, while JEM assigns high energy to out-of-distribution regions and samples data modes via Langevin dynamics (SGLD).'
      }
    >
      <ControlRow label="Model & view">
        <Select label="Dataset" value={dataChoice} options={DATASETS} onChange={(v) => setDataChoice(v as any)} />
        <Select label="Model" value={modelType} options={MODELS} onChange={(v) => setModelType(v as any)} />
        <Select
          label="Surface visualisation"
          value={viewType}
          options={VIEWS}
          onChange={(v) => setViewType(v as any)}
        />
      </ControlRow>

      <ControlRow label="Training progression">
        <Player count={Math.max(1, numCheckpoints)} value={currentIdx} onChange={setCheckpointIndex} />
      </ControlRow>

      <Plots>
        <Plot x={planeAxisX} y={planeAxisY} title="State space, energy surface & SGLD negative samples">
          {surfaceMatrix.length > 0 && gridAxis.length > 0 && (
            <Raster x={gridAxis} y={gridAxis} z={surfaceMatrix} scale="diverging" />
          )}
          <Points x={trainPoints.c0.x} y={trainPoints.c0.y} slot={0} size={4} />
          <Points x={trainPoints.c1.x} y={trainPoints.c1.y} slot={1} size={4} />
          {negativeSamples.x.length > 0 && (
            <Points x={negativeSamples.x} y={negativeSamples.y} slot={2} size={5} thin={true} />
          )}
        </Plot>

        <Plot x={lossX} y={lossY} title="Classification Cross-Entropy Loss">
          <Curve x={lossSteps} y={ceLoss} slot={0} />
        </Plot>
      </Plots>

      <ControlRow label="Diagnostics">
        <Readout
          label="Accuracy"
          value={currentCheckpoint ? `${formatNumber(Number((currentCheckpoint.accuracy * 100).toFixed(1)))}%` : '—'}
        />
        <Readout
          label="Calibration (ECE)"
          value={currentCheckpoint ? formatNumber(Number(currentCheckpoint.ece.toFixed(3))) : '—'}
        />
        <Readout
          label="Mean Data Energy"
          value={!Number.isNaN(meanDataEnergy) ? formatNumber(Number(meanDataEnergy.toFixed(2))) : '—'}
        />
        <Readout
          label="OOD AUROC"
          value={currentCheckpoint ? formatNumber(Number(currentCheckpoint.oodAuroc.toFixed(2))) : '—'}
        />
      </ControlRow>
    </Figure>
  )
}
