import { normal, stream, type Stream, uniform } from 'aifn-compute/foundation/random'
import { logGamma } from 'aifn-compute/numerics/special'

export const V = 9
export const K = 6

/**
 * The "bars" topics of Griffiths and Steyvers on a 3 × 3 grid of words: three row topics and three column topics,
 * each uniform over its three words. Word w sits at row ⌊w/3⌋, column w mod 3.
 */
export const TRUE_TOPICS: number[][] = [
  ...[0, 1, 2].map((r) => Array.from({ length: V }, (_, w) => (Math.floor(w / 3) === r ? 1 / 3 : 0))),
  ...[0, 1, 2].map((c) => Array.from({ length: V }, (_, w) => (w % 3 === c ? 1 / 3 : 0))),
]

/** Draw from a symmetric Dirichlet(a) via normalised gamma draws (Marsaglia–Tsang, boosted for a < 1). */
function dirichlet(r: Stream, a: number, k: number): number[] {
  const gamma = (shape: number): number => {
    if (shape < 1) return gamma(shape + 1) * Math.pow(uniform(r), 1 / shape)
    const d = shape - 1 / 3
    const c = 1 / Math.sqrt(9 * d)
    for (;;) {
      const x = normal(r)
      const v = (1 + c * x) ** 3
      if (v > 0 && Math.log(uniform(r)) < 0.5 * x * x + d - d * v + d * Math.log(v)) return d * v
    }
  }
  const g = Array.from({ length: k }, () => gamma(a))
  const s = g.reduce((x, y) => x + y, 0)
  return g.map((v) => v / s)
}

const draw = (r: Stream, p: number[]) => {
  let u = uniform(r) * p.reduce((a, b) => a + b, 0)
  for (let i = 0; i < p.length; i++) if ((u -= p[i]) <= 0) return i
  return p.length - 1
}

/** A corpus generated by LDA with the bars topics: each document mixes topics with weights drawn from Dir(0.3). */
export function corpus(docs: number, length: number, seed: number): number[][] {
  const r = stream(seed)
  return Array.from({ length: docs }, () => {
    const theta = dirichlet(r, 0.3, K)
    return Array.from({ length }, () => draw(r, TRUE_TOPICS[draw(r, theta)]))
  })
}

export type State = {
  z: number[][]
  ndk: number[][]
  nkw: number[][]
  nk: number[]
  sweep: number
  seed: number
}

/** Random initial topic assignments and their counts. */
export function initialise(docs: number[][], seed: number): State {
  const r = stream(seed)
  const ndk = docs.map(() => new Array<number>(K).fill(0))
  const nkw = Array.from({ length: K }, () => new Array<number>(V).fill(0))
  const nk = new Array<number>(K).fill(0)
  const z = docs.map((doc, d) =>
    doc.map((w) => {
      const k = Math.floor(uniform(r) * K)
      ndk[d][k]++
      nkw[k][w]++
      nk[k]++
      return k
    }),
  )
  return { z, ndk, nkw, nk, sweep: 0, seed }
}

/**
 * One sweep of collapsed Gibbs sampling: every token's topic is resampled from
 * p(z = k | rest) ∝ (n_dk + α)(n_kw + β)/(n_k + Vβ), with the token's own counts removed.
 */
export function sweep(docs: number[][], s: State, alpha: number, beta: number): State {
  const r = stream(s.seed * 1000 + s.sweep + 1)
  const z = s.z.map((row) => [...row])
  const ndk = s.ndk.map((row) => [...row])
  const nkw = s.nkw.map((row) => [...row])
  const nk = [...s.nk]
  const p = new Array<number>(K)
  docs.forEach((doc, d) => {
    doc.forEach((w, i) => {
      const old = z[d][i]
      ndk[d][old]--
      nkw[old][w]--
      nk[old]--
      for (let k = 0; k < K; k++) p[k] = ((ndk[d][k] + alpha) * (nkw[k][w] + beta)) / (nk[k] + V * beta)
      const k = draw(r, p)
      z[d][i] = k
      ndk[d][k]++
      nkw[k][w]++
      nk[k]++
    })
  })
  return { z, ndk, nkw, nk, sweep: s.sweep + 1, seed: s.seed }
}

/** Point estimate of the topic–word distributions: φ_kw = (n_kw + β)/(n_k + Vβ). */
export const topicWord = (s: State, beta: number) =>
  s.nkw.map((row, k) => row.map((n) => (n + beta) / (s.nk[k] + V * beta)))

/** log p(w | z), with the topic–word distributions integrated out. */
export function logLikelihood(s: State, beta: number): number {
  return s.nkw.reduce(
    (total, row, k) =>
      total +
      logGamma(V * beta) -
      V * logGamma(beta) +
      row.reduce((a, n) => a + logGamma(n + beta), 0) -
      logGamma(s.nk[k] + V * beta),
    0,
  )
}

/** Mean, over learned topics, of the total variation distance to the closest true topic. */
export function distanceToTruth(phi: number[][]): number {
  const tv = (a: number[], b: number[]) => 0.5 * a.reduce((s, v, i) => s + Math.abs(v - b[i]), 0)
  return phi.reduce((s, row) => s + Math.min(...TRUE_TOPICS.map((t) => tv(row, t))), 0) / phi.length
}
